/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SchoolAdminsRouteImport } from './routes/school-admins'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminSupportRouteImport } from './routes/super-admin.support'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin.schools'
import { Route as SuperAdminSchoolAdminsRouteImport } from './routes/super-admin.school-admins'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminApplicationsRouteImport } from './routes/super-admin.applications'
import { Route as SuperAdminAnnouncementsRouteImport } from './routes/super-admin.announcements'
import { Route as SuperAdminActivityRouteImport } from './routes/super-admin.activity'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAdminsRoute = SchoolAdminsRouteImport.update({
  id: '/school-admins',
  path: '/school-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSupportRoute = SuperAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolAdminsRoute = SuperAdminSchoolAdminsRouteImport.update({
  id: '/school-admins',
  path: '/school-admins',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminApplicationsRoute = SuperAdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnnouncementsRoute = SuperAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminActivityRoute = SuperAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/announcements': typeof AnnouncementsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/homepage': typeof HomepageRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/school-admins': typeof SchoolAdminsRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/school-admins': typeof SuperAdminSchoolAdminsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/announcements': typeof AnnouncementsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/homepage': typeof HomepageRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/school-admins': typeof SchoolAdminsRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/school-admins': typeof SuperAdminSchoolAdminsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/announcements': typeof AnnouncementsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/homepage': typeof HomepageRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/school-admins': typeof SchoolAdminsRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/school-admins': typeof SuperAdminSchoolAdminsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/announcements'
    | '/applications'
    | '/auth'
    | '/homepage'
    | '/payments'
    | '/reports'
    | '/school-admins'
    | '/schools'
    | '/settings'
    | '/super-admin'
    | '/support'
    | '/super-admin/activity'
    | '/super-admin/announcements'
    | '/super-admin/applications'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/school-admins'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/support'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/announcements'
    | '/applications'
    | '/auth'
    | '/homepage'
    | '/payments'
    | '/reports'
    | '/school-admins'
    | '/schools'
    | '/settings'
    | '/support'
    | '/super-admin/activity'
    | '/super-admin/announcements'
    | '/super-admin/applications'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/school-admins'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/support'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/announcements'
    | '/applications'
    | '/auth'
    | '/homepage'
    | '/payments'
    | '/reports'
    | '/school-admins'
    | '/schools'
    | '/settings'
    | '/super-admin'
    | '/support'
    | '/super-admin/activity'
    | '/super-admin/announcements'
    | '/super-admin/applications'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/school-admins'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/support'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  HomepageRoute: typeof HomepageRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SchoolAdminsRoute: typeof SchoolAdminsRoute
  SchoolsRoute: typeof SchoolsRoute
  SettingsRoute: typeof SettingsRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-admins': {
      id: '/school-admins'
      path: '/school-admins'
      fullPath: '/school-admins'
      preLoaderRoute: typeof SchoolAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/support': {
      id: '/super-admin/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof SuperAdminSupportRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/schools': {
      id: '/super-admin/schools'
      path: '/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof SuperAdminSchoolsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/school-admins': {
      id: '/super-admin/school-admins'
      path: '/school-admins'
      fullPath: '/super-admin/school-admins'
      preLoaderRoute: typeof SuperAdminSchoolAdminsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/applications': {
      id: '/super-admin/applications'
      path: '/applications'
      fullPath: '/super-admin/applications'
      preLoaderRoute: typeof SuperAdminApplicationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/announcements': {
      id: '/super-admin/announcements'
      path: '/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof SuperAdminAnnouncementsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/activity': {
      id: '/super-admin/activity'
      path: '/activity'
      fullPath: '/super-admin/activity'
      preLoaderRoute: typeof SuperAdminActivityRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminActivityRoute: typeof SuperAdminActivityRoute
  SuperAdminAnnouncementsRoute: typeof SuperAdminAnnouncementsRoute
  SuperAdminApplicationsRoute: typeof SuperAdminApplicationsRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminSchoolAdminsRoute: typeof SuperAdminSchoolAdminsRoute
  SuperAdminSchoolsRoute: typeof SuperAdminSchoolsRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSupportRoute: typeof SuperAdminSupportRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminActivityRoute: SuperAdminActivityRoute,
  SuperAdminAnnouncementsRoute: SuperAdminAnnouncementsRoute,
  SuperAdminApplicationsRoute: SuperAdminApplicationsRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminSchoolAdminsRoute: SuperAdminSchoolAdminsRoute,
  SuperAdminSchoolsRoute: SuperAdminSchoolsRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSupportRoute: SuperAdminSupportRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  HomepageRoute: HomepageRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SchoolAdminsRoute: SchoolAdminsRoute,
  SchoolsRoute: SchoolsRoute,
  SettingsRoute: SettingsRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
