/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SchoolAdminsRouteImport } from './routes/school-admins'
import { Route as SchoolAdminRouteImport } from './routes/school-admin'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminSupportRouteImport } from './routes/super-admin.support'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSchoolsRouteImport } from './routes/super-admin.schools'
import { Route as SuperAdminSchoolAdminsRouteImport } from './routes/super-admin.school-admins'
import { Route as SuperAdminSchoolAdminApplicationsRouteImport } from './routes/super-admin.school-admin-applications'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminPaymentsRouteImport } from './routes/super-admin.payments'
import { Route as SuperAdminApplicationsRouteImport } from './routes/super-admin.applications'
import { Route as SuperAdminAnnouncementsRouteImport } from './routes/super-admin.announcements'
import { Route as SuperAdminActivityRouteImport } from './routes/super-admin.activity'
import { Route as SchoolAdminSettingsRouteImport } from './routes/school-admin.settings'
import { Route as SchoolAdminSchoolProfileRouteImport } from './routes/school-admin.school-profile'
import { Route as SchoolAdminReportsRouteImport } from './routes/school-admin.reports'
import { Route as SchoolAdminReportCardsRouteImport } from './routes/school-admin.report-cards'
import { Route as SchoolAdminPrincipalManagementRouteImport } from './routes/school-admin.principal-management'
import { Route as SchoolAdminInstructionsRouteImport } from './routes/school-admin.instructions'
import { Route as SchoolAdminDocumentsRouteImport } from './routes/school-admin.documents'
import { Route as SchoolAdminDashboardRouteImport } from './routes/school-admin.dashboard'
import { Route as SchoolAdminAttendanceRouteImport } from './routes/school-admin.attendance'
import { Route as SchoolAdminAnalyticsRouteImport } from './routes/school-admin.analytics'
import { Route as SchoolAdminAcademicRouteImport } from './routes/school-admin.academic'
import { Route as RegisterSchoolAdminRouteImport } from './routes/register.school-admin'
import { Route as RegisterSchoolRouteImport } from './routes/register.school'
import { Route as AuthSetupPasswordRouteImport } from './routes/auth.setup-password'
import { Route as RegisterSchoolAdminStatusRouteImport } from './routes/register.school-admin.status'
import { Route as RegisterSchoolAdminPendingRouteImport } from './routes/register.school-admin.pending'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAdminsRoute = SchoolAdminsRouteImport.update({
  id: '/school-admins',
  path: '/school-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAdminRoute = SchoolAdminRouteImport.update({
  id: '/school-admin',
  path: '/school-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSupportRoute = SuperAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolsRoute = SuperAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolAdminsRoute = SuperAdminSchoolAdminsRouteImport.update({
  id: '/school-admins',
  path: '/school-admins',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSchoolAdminApplicationsRoute =
  SuperAdminSchoolAdminApplicationsRouteImport.update({
    id: '/school-admin-applications',
    path: '/school-admin-applications',
    getParentRoute: () => SuperAdminRoute,
  } as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminPaymentsRoute = SuperAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminApplicationsRoute = SuperAdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnnouncementsRoute = SuperAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminActivityRoute = SuperAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SchoolAdminSettingsRoute = SchoolAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminSchoolProfileRoute =
  SchoolAdminSchoolProfileRouteImport.update({
    id: '/school-profile',
    path: '/school-profile',
    getParentRoute: () => SchoolAdminRoute,
  } as any)
const SchoolAdminReportsRoute = SchoolAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminReportCardsRoute = SchoolAdminReportCardsRouteImport.update({
  id: '/report-cards',
  path: '/report-cards',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminPrincipalManagementRoute =
  SchoolAdminPrincipalManagementRouteImport.update({
    id: '/principal-management',
    path: '/principal-management',
    getParentRoute: () => SchoolAdminRoute,
  } as any)
const SchoolAdminInstructionsRoute = SchoolAdminInstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminDocumentsRoute = SchoolAdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminDashboardRoute = SchoolAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminAttendanceRoute = SchoolAdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminAnalyticsRoute = SchoolAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const SchoolAdminAcademicRoute = SchoolAdminAcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => SchoolAdminRoute,
} as any)
const RegisterSchoolAdminRoute = RegisterSchoolAdminRouteImport.update({
  id: '/register/school-admin',
  path: '/register/school-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterSchoolRoute = RegisterSchoolRouteImport.update({
  id: '/register/school',
  path: '/register/school',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetupPasswordRoute = AuthSetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => AuthRoute,
} as any)
const RegisterSchoolAdminStatusRoute =
  RegisterSchoolAdminStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => RegisterSchoolAdminRoute,
  } as any)
const RegisterSchoolAdminPendingRoute =
  RegisterSchoolAdminPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => RegisterSchoolAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/announcements': typeof AnnouncementsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRouteWithChildren
  '/homepage': typeof HomepageRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/school-admin': typeof SchoolAdminRouteWithChildren
  '/school-admins': typeof SchoolAdminsRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/register/school': typeof RegisterSchoolRoute
  '/register/school-admin': typeof RegisterSchoolAdminRouteWithChildren
  '/school-admin/academic': typeof SchoolAdminAcademicRoute
  '/school-admin/analytics': typeof SchoolAdminAnalyticsRoute
  '/school-admin/attendance': typeof SchoolAdminAttendanceRoute
  '/school-admin/dashboard': typeof SchoolAdminDashboardRoute
  '/school-admin/documents': typeof SchoolAdminDocumentsRoute
  '/school-admin/instructions': typeof SchoolAdminInstructionsRoute
  '/school-admin/principal-management': typeof SchoolAdminPrincipalManagementRoute
  '/school-admin/report-cards': typeof SchoolAdminReportCardsRoute
  '/school-admin/reports': typeof SchoolAdminReportsRoute
  '/school-admin/school-profile': typeof SchoolAdminSchoolProfileRoute
  '/school-admin/settings': typeof SchoolAdminSettingsRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/school-admin-applications': typeof SuperAdminSchoolAdminApplicationsRoute
  '/super-admin/school-admins': typeof SuperAdminSchoolAdminsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/register/school-admin/pending': typeof RegisterSchoolAdminPendingRoute
  '/register/school-admin/status': typeof RegisterSchoolAdminStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/announcements': typeof AnnouncementsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRouteWithChildren
  '/homepage': typeof HomepageRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/school-admin': typeof SchoolAdminRouteWithChildren
  '/school-admins': typeof SchoolAdminsRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/register/school': typeof RegisterSchoolRoute
  '/register/school-admin': typeof RegisterSchoolAdminRouteWithChildren
  '/school-admin/academic': typeof SchoolAdminAcademicRoute
  '/school-admin/analytics': typeof SchoolAdminAnalyticsRoute
  '/school-admin/attendance': typeof SchoolAdminAttendanceRoute
  '/school-admin/dashboard': typeof SchoolAdminDashboardRoute
  '/school-admin/documents': typeof SchoolAdminDocumentsRoute
  '/school-admin/instructions': typeof SchoolAdminInstructionsRoute
  '/school-admin/principal-management': typeof SchoolAdminPrincipalManagementRoute
  '/school-admin/report-cards': typeof SchoolAdminReportCardsRoute
  '/school-admin/reports': typeof SchoolAdminReportsRoute
  '/school-admin/school-profile': typeof SchoolAdminSchoolProfileRoute
  '/school-admin/settings': typeof SchoolAdminSettingsRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/school-admin-applications': typeof SuperAdminSchoolAdminApplicationsRoute
  '/super-admin/school-admins': typeof SuperAdminSchoolAdminsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/register/school-admin/pending': typeof RegisterSchoolAdminPendingRoute
  '/register/school-admin/status': typeof RegisterSchoolAdminStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/announcements': typeof AnnouncementsRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRouteWithChildren
  '/homepage': typeof HomepageRoute
  '/payments': typeof PaymentsRoute
  '/reports': typeof ReportsRoute
  '/school-admin': typeof SchoolAdminRouteWithChildren
  '/school-admins': typeof SchoolAdminsRoute
  '/schools': typeof SchoolsRoute
  '/settings': typeof SettingsRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/support': typeof SupportRoute
  '/auth/setup-password': typeof AuthSetupPasswordRoute
  '/register/school': typeof RegisterSchoolRoute
  '/register/school-admin': typeof RegisterSchoolAdminRouteWithChildren
  '/school-admin/academic': typeof SchoolAdminAcademicRoute
  '/school-admin/analytics': typeof SchoolAdminAnalyticsRoute
  '/school-admin/attendance': typeof SchoolAdminAttendanceRoute
  '/school-admin/dashboard': typeof SchoolAdminDashboardRoute
  '/school-admin/documents': typeof SchoolAdminDocumentsRoute
  '/school-admin/instructions': typeof SchoolAdminInstructionsRoute
  '/school-admin/principal-management': typeof SchoolAdminPrincipalManagementRoute
  '/school-admin/report-cards': typeof SchoolAdminReportCardsRoute
  '/school-admin/reports': typeof SchoolAdminReportsRoute
  '/school-admin/school-profile': typeof SchoolAdminSchoolProfileRoute
  '/school-admin/settings': typeof SchoolAdminSettingsRoute
  '/super-admin/activity': typeof SuperAdminActivityRoute
  '/super-admin/announcements': typeof SuperAdminAnnouncementsRoute
  '/super-admin/applications': typeof SuperAdminApplicationsRoute
  '/super-admin/payments': typeof SuperAdminPaymentsRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/school-admin-applications': typeof SuperAdminSchoolAdminApplicationsRoute
  '/super-admin/school-admins': typeof SuperAdminSchoolAdminsRoute
  '/super-admin/schools': typeof SuperAdminSchoolsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/support': typeof SuperAdminSupportRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/register/school-admin/pending': typeof RegisterSchoolAdminPendingRoute
  '/register/school-admin/status': typeof RegisterSchoolAdminStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/announcements'
    | '/applications'
    | '/auth'
    | '/homepage'
    | '/payments'
    | '/reports'
    | '/school-admin'
    | '/school-admins'
    | '/schools'
    | '/settings'
    | '/super-admin'
    | '/support'
    | '/auth/setup-password'
    | '/register/school'
    | '/register/school-admin'
    | '/school-admin/academic'
    | '/school-admin/analytics'
    | '/school-admin/attendance'
    | '/school-admin/dashboard'
    | '/school-admin/documents'
    | '/school-admin/instructions'
    | '/school-admin/principal-management'
    | '/school-admin/report-cards'
    | '/school-admin/reports'
    | '/school-admin/school-profile'
    | '/school-admin/settings'
    | '/super-admin/activity'
    | '/super-admin/announcements'
    | '/super-admin/applications'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/school-admin-applications'
    | '/super-admin/school-admins'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/support'
    | '/super-admin/'
    | '/register/school-admin/pending'
    | '/register/school-admin/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/announcements'
    | '/applications'
    | '/auth'
    | '/homepage'
    | '/payments'
    | '/reports'
    | '/school-admin'
    | '/school-admins'
    | '/schools'
    | '/settings'
    | '/support'
    | '/auth/setup-password'
    | '/register/school'
    | '/register/school-admin'
    | '/school-admin/academic'
    | '/school-admin/analytics'
    | '/school-admin/attendance'
    | '/school-admin/dashboard'
    | '/school-admin/documents'
    | '/school-admin/instructions'
    | '/school-admin/principal-management'
    | '/school-admin/report-cards'
    | '/school-admin/reports'
    | '/school-admin/school-profile'
    | '/school-admin/settings'
    | '/super-admin/activity'
    | '/super-admin/announcements'
    | '/super-admin/applications'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/school-admin-applications'
    | '/super-admin/school-admins'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/support'
    | '/super-admin'
    | '/register/school-admin/pending'
    | '/register/school-admin/status'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/announcements'
    | '/applications'
    | '/auth'
    | '/homepage'
    | '/payments'
    | '/reports'
    | '/school-admin'
    | '/school-admins'
    | '/schools'
    | '/settings'
    | '/super-admin'
    | '/support'
    | '/auth/setup-password'
    | '/register/school'
    | '/register/school-admin'
    | '/school-admin/academic'
    | '/school-admin/analytics'
    | '/school-admin/attendance'
    | '/school-admin/dashboard'
    | '/school-admin/documents'
    | '/school-admin/instructions'
    | '/school-admin/principal-management'
    | '/school-admin/report-cards'
    | '/school-admin/reports'
    | '/school-admin/school-profile'
    | '/school-admin/settings'
    | '/super-admin/activity'
    | '/super-admin/announcements'
    | '/super-admin/applications'
    | '/super-admin/payments'
    | '/super-admin/reports'
    | '/super-admin/school-admin-applications'
    | '/super-admin/school-admins'
    | '/super-admin/schools'
    | '/super-admin/settings'
    | '/super-admin/support'
    | '/super-admin/'
    | '/register/school-admin/pending'
    | '/register/school-admin/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRouteWithChildren
  HomepageRoute: typeof HomepageRoute
  PaymentsRoute: typeof PaymentsRoute
  ReportsRoute: typeof ReportsRoute
  SchoolAdminRoute: typeof SchoolAdminRouteWithChildren
  SchoolAdminsRoute: typeof SchoolAdminsRoute
  SchoolsRoute: typeof SchoolsRoute
  SettingsRoute: typeof SettingsRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  SupportRoute: typeof SupportRoute
  RegisterSchoolRoute: typeof RegisterSchoolRoute
  RegisterSchoolAdminRoute: typeof RegisterSchoolAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-admins': {
      id: '/school-admins'
      path: '/school-admins'
      fullPath: '/school-admins'
      preLoaderRoute: typeof SchoolAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-admin': {
      id: '/school-admin'
      path: '/school-admin'
      fullPath: '/school-admin'
      preLoaderRoute: typeof SchoolAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/support': {
      id: '/super-admin/support'
      path: '/support'
      fullPath: '/super-admin/support'
      preLoaderRoute: typeof SuperAdminSupportRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/schools': {
      id: '/super-admin/schools'
      path: '/schools'
      fullPath: '/super-admin/schools'
      preLoaderRoute: typeof SuperAdminSchoolsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/school-admins': {
      id: '/super-admin/school-admins'
      path: '/school-admins'
      fullPath: '/super-admin/school-admins'
      preLoaderRoute: typeof SuperAdminSchoolAdminsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/school-admin-applications': {
      id: '/super-admin/school-admin-applications'
      path: '/school-admin-applications'
      fullPath: '/super-admin/school-admin-applications'
      preLoaderRoute: typeof SuperAdminSchoolAdminApplicationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/payments': {
      id: '/super-admin/payments'
      path: '/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperAdminPaymentsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/applications': {
      id: '/super-admin/applications'
      path: '/applications'
      fullPath: '/super-admin/applications'
      preLoaderRoute: typeof SuperAdminApplicationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/announcements': {
      id: '/super-admin/announcements'
      path: '/announcements'
      fullPath: '/super-admin/announcements'
      preLoaderRoute: typeof SuperAdminAnnouncementsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/activity': {
      id: '/super-admin/activity'
      path: '/activity'
      fullPath: '/super-admin/activity'
      preLoaderRoute: typeof SuperAdminActivityRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/school-admin/settings': {
      id: '/school-admin/settings'
      path: '/settings'
      fullPath: '/school-admin/settings'
      preLoaderRoute: typeof SchoolAdminSettingsRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/school-profile': {
      id: '/school-admin/school-profile'
      path: '/school-profile'
      fullPath: '/school-admin/school-profile'
      preLoaderRoute: typeof SchoolAdminSchoolProfileRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/reports': {
      id: '/school-admin/reports'
      path: '/reports'
      fullPath: '/school-admin/reports'
      preLoaderRoute: typeof SchoolAdminReportsRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/report-cards': {
      id: '/school-admin/report-cards'
      path: '/report-cards'
      fullPath: '/school-admin/report-cards'
      preLoaderRoute: typeof SchoolAdminReportCardsRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/principal-management': {
      id: '/school-admin/principal-management'
      path: '/principal-management'
      fullPath: '/school-admin/principal-management'
      preLoaderRoute: typeof SchoolAdminPrincipalManagementRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/instructions': {
      id: '/school-admin/instructions'
      path: '/instructions'
      fullPath: '/school-admin/instructions'
      preLoaderRoute: typeof SchoolAdminInstructionsRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/documents': {
      id: '/school-admin/documents'
      path: '/documents'
      fullPath: '/school-admin/documents'
      preLoaderRoute: typeof SchoolAdminDocumentsRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/dashboard': {
      id: '/school-admin/dashboard'
      path: '/dashboard'
      fullPath: '/school-admin/dashboard'
      preLoaderRoute: typeof SchoolAdminDashboardRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/attendance': {
      id: '/school-admin/attendance'
      path: '/attendance'
      fullPath: '/school-admin/attendance'
      preLoaderRoute: typeof SchoolAdminAttendanceRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/analytics': {
      id: '/school-admin/analytics'
      path: '/analytics'
      fullPath: '/school-admin/analytics'
      preLoaderRoute: typeof SchoolAdminAnalyticsRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/school-admin/academic': {
      id: '/school-admin/academic'
      path: '/academic'
      fullPath: '/school-admin/academic'
      preLoaderRoute: typeof SchoolAdminAcademicRouteImport
      parentRoute: typeof SchoolAdminRoute
    }
    '/register/school-admin': {
      id: '/register/school-admin'
      path: '/register/school-admin'
      fullPath: '/register/school-admin'
      preLoaderRoute: typeof RegisterSchoolAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/school': {
      id: '/register/school'
      path: '/register/school'
      fullPath: '/register/school'
      preLoaderRoute: typeof RegisterSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/setup-password': {
      id: '/auth/setup-password'
      path: '/setup-password'
      fullPath: '/auth/setup-password'
      preLoaderRoute: typeof AuthSetupPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/register/school-admin/status': {
      id: '/register/school-admin/status'
      path: '/status'
      fullPath: '/register/school-admin/status'
      preLoaderRoute: typeof RegisterSchoolAdminStatusRouteImport
      parentRoute: typeof RegisterSchoolAdminRoute
    }
    '/register/school-admin/pending': {
      id: '/register/school-admin/pending'
      path: '/pending'
      fullPath: '/register/school-admin/pending'
      preLoaderRoute: typeof RegisterSchoolAdminPendingRouteImport
      parentRoute: typeof RegisterSchoolAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSetupPasswordRoute: typeof AuthSetupPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSetupPasswordRoute: AuthSetupPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SchoolAdminRouteChildren {
  SchoolAdminAcademicRoute: typeof SchoolAdminAcademicRoute
  SchoolAdminAnalyticsRoute: typeof SchoolAdminAnalyticsRoute
  SchoolAdminAttendanceRoute: typeof SchoolAdminAttendanceRoute
  SchoolAdminDashboardRoute: typeof SchoolAdminDashboardRoute
  SchoolAdminDocumentsRoute: typeof SchoolAdminDocumentsRoute
  SchoolAdminInstructionsRoute: typeof SchoolAdminInstructionsRoute
  SchoolAdminPrincipalManagementRoute: typeof SchoolAdminPrincipalManagementRoute
  SchoolAdminReportCardsRoute: typeof SchoolAdminReportCardsRoute
  SchoolAdminReportsRoute: typeof SchoolAdminReportsRoute
  SchoolAdminSchoolProfileRoute: typeof SchoolAdminSchoolProfileRoute
  SchoolAdminSettingsRoute: typeof SchoolAdminSettingsRoute
}

const SchoolAdminRouteChildren: SchoolAdminRouteChildren = {
  SchoolAdminAcademicRoute: SchoolAdminAcademicRoute,
  SchoolAdminAnalyticsRoute: SchoolAdminAnalyticsRoute,
  SchoolAdminAttendanceRoute: SchoolAdminAttendanceRoute,
  SchoolAdminDashboardRoute: SchoolAdminDashboardRoute,
  SchoolAdminDocumentsRoute: SchoolAdminDocumentsRoute,
  SchoolAdminInstructionsRoute: SchoolAdminInstructionsRoute,
  SchoolAdminPrincipalManagementRoute: SchoolAdminPrincipalManagementRoute,
  SchoolAdminReportCardsRoute: SchoolAdminReportCardsRoute,
  SchoolAdminReportsRoute: SchoolAdminReportsRoute,
  SchoolAdminSchoolProfileRoute: SchoolAdminSchoolProfileRoute,
  SchoolAdminSettingsRoute: SchoolAdminSettingsRoute,
}

const SchoolAdminRouteWithChildren = SchoolAdminRoute._addFileChildren(
  SchoolAdminRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminActivityRoute: typeof SuperAdminActivityRoute
  SuperAdminAnnouncementsRoute: typeof SuperAdminAnnouncementsRoute
  SuperAdminApplicationsRoute: typeof SuperAdminApplicationsRoute
  SuperAdminPaymentsRoute: typeof SuperAdminPaymentsRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminSchoolAdminApplicationsRoute: typeof SuperAdminSchoolAdminApplicationsRoute
  SuperAdminSchoolAdminsRoute: typeof SuperAdminSchoolAdminsRoute
  SuperAdminSchoolsRoute: typeof SuperAdminSchoolsRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminSupportRoute: typeof SuperAdminSupportRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminActivityRoute: SuperAdminActivityRoute,
  SuperAdminAnnouncementsRoute: SuperAdminAnnouncementsRoute,
  SuperAdminApplicationsRoute: SuperAdminApplicationsRoute,
  SuperAdminPaymentsRoute: SuperAdminPaymentsRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminSchoolAdminApplicationsRoute:
    SuperAdminSchoolAdminApplicationsRoute,
  SuperAdminSchoolAdminsRoute: SuperAdminSchoolAdminsRoute,
  SuperAdminSchoolsRoute: SuperAdminSchoolsRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminSupportRoute: SuperAdminSupportRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

interface RegisterSchoolAdminRouteChildren {
  RegisterSchoolAdminPendingRoute: typeof RegisterSchoolAdminPendingRoute
  RegisterSchoolAdminStatusRoute: typeof RegisterSchoolAdminStatusRoute
}

const RegisterSchoolAdminRouteChildren: RegisterSchoolAdminRouteChildren = {
  RegisterSchoolAdminPendingRoute: RegisterSchoolAdminPendingRoute,
  RegisterSchoolAdminStatusRoute: RegisterSchoolAdminStatusRoute,
}

const RegisterSchoolAdminRouteWithChildren =
  RegisterSchoolAdminRoute._addFileChildren(RegisterSchoolAdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRouteWithChildren,
  HomepageRoute: HomepageRoute,
  PaymentsRoute: PaymentsRoute,
  ReportsRoute: ReportsRoute,
  SchoolAdminRoute: SchoolAdminRouteWithChildren,
  SchoolAdminsRoute: SchoolAdminsRoute,
  SchoolsRoute: SchoolsRoute,
  SettingsRoute: SettingsRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute: SupportRoute,
  RegisterSchoolRoute: RegisterSchoolRoute,
  RegisterSchoolAdminRoute: RegisterSchoolAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
